const testimonials = [
  {
    id: 8,
    name: "Diego",
    time: "8 anos no Airbnb",
    date: "2026-05-01",
    stayDuration: "Ficou algumas noites",
    rating: 5,
    comment: [
      "Atesto o que li em outra avaliação: é uma verdadeira poesia em forma de casa! Linda, aconchegante, privativa e completa. ",
      "Foi sensacional os momentos vividos nessa casa junto com minha esposa, levaremos as recordações para sempre com muito carinho e afeto. Passamos 5 dias e, se pudéssemos, ficaríamos por semanas, meses… Fácil acesso para toda a Rota dos Milagres. Um dia voltaremos 💚",
    ],
    image: null,
  },
  {
    id: 9,
    name: "Pedro",
    time: "12 anos no Airbnb",
    date: "2026-02-01",
    stayDuration: "Ficou algumas noites",
    rating: 5,
    comment: [
      "A casa é um sonho e com certeza foi além das nossas expectativas. Tudo com um bom gosto absurdo, além da piscina, que também é um diferencial. ",
      "Recomendo para todos! Tudo maravilhoso e incrível. Voltaria com certeza.",
    ],
    image: null,
  },
  {
    id: 10,
    name: "Márcia",
    time: "10 anos no Airbnb",
    date: "2026-03-01",
    stayDuration: "Ficou algumas noites",
    rating: 5,
    comment: [
      "Lugar simplesmente incrível! Uma paz absurda, perfeito pra descansar e desligar do mundo. Já quero voltar!",
    ],
    image: null,
  },
  {
    id: 11,
    name: "Lucas",
    time: "10 anos no Airbnb",
    date: "2026-01-01",
    stayDuration: "Ficou algumas noites",
    rating: 5,
    comment: [
      "Excelente estadia na Rota dos Milagres, na Praia do Patacho (Porto de Pedras). Foi a nossa primeira vez na região e, após dias explorando as redondezas, chegamos à conclusão de que a localização e a casa foram uma das melhores opções que poderíamos ter encontrado. ",
      "A casa é de grande porte, bastante confortável para dois adultos. O capricho com o espaço é enorme e recomendamos muito a estadia, torcendo desde já para ter a oportunidade de voltar!",
    ],
    image: null,
  },
  {
    id: 12,
    name: "Karoline",
    time: "7 anos no Airbnb",
    date: "2026-04-01",
    stayDuration: "Ficou algumas noites",
    rating: 5,
    comment: [
      "Gostamos muito da hospedagem. Local muito aconchegante e agradável, equipado com tudo que precisamos! Localização muito boa.",
    ],
    image: null,
  },
  {
    id: 13,
    name: "Larissa",
    time: "9 anos no Airbnb",
    date: "2025-11-01",
    stayDuration: "Ficou algumas noites",
    rating: 5,
    comment: [
      "A estadia foi incrível: a casa é belíssima, confortável e super bem equipada, fácil de encontrar e aconchegante. Nos mínimos detalhes, percebe-se o zelo e a preocupação em receber bem os hóspedes. ",
      "O café da manhã é delicioso e bem servido. Passamos dias maravilhosos e, sem dúvidas, voltaremos!",
    ],
    image: null,
  },
  {
    id: 14,
    name: "Ana Paula",
    time: "11 anos no Airbnb",
    date: "2026-02-01",
    stayDuration: "Ficou algumas noites",
    rating: 5,
    comment: [
      "A casa é muito aconchegante, arrumadinha e confortável. Recomendamos!",
    ],
    image: null,
  },
  {
    id: 15,
    name: "Patrick",
    time: "6 anos no Airbnb",
    date: "2025-12-01",
    stayDuration: "Ficou em torno de uma semana",
    rating: 5,
    comment: [
      "Sem palavras para descrever os dias na Casa Ella. Localização ótima, perto de muitas praias do Circuito dos Milagres. Casa linda, jardim lindo, piscina bem cuidada, cama gostosa, cozinha completa e, acima de tudo, atenção exemplar por parte das anfitriãs. ",
      "Café da manhã todos os dias, fresquinho, com o melhor da culinária local. Obrigado por toda a atenção e voltarei com certeza ❤️",
    ],
    image: null,
  },
  {
    id: 16,
    name: "Pedro",
    time: "10 anos no Airbnb",
    date: "2026-01-01",
    stayDuration: "Ficou algumas noites",
    rating: 5,
    comment: [
      "Excelente casa, melhor do que nas fotos. Localização excelente, perto das melhores praias de Milagres. Provavelmente irei voltar. Tudo limpo e organizado.",
    ],
    image: null,
  },
  {
    id: 1,
    name: "Rejane",
    time: "Comentário via Airbnb",
    date: "2024-11-01",
    stayDuration: "Ficou algumas noites",
    rating: 5,
    comment: [
      "O espaço é encantador e ainda mais bonito e completo do que nas fotos. ",
      "Café da manhã delicioso feito diariamente pela Juliana, com todo o necessário. ",
      "Acomodação espaçosa e perto de uma das mais belas praias da Rota (Patacho). ",
      "Voltaria com toda a certeza!",
    ],
    image: "/midias/testimonials/rejane.webp",
  },
  {
    id: 2,
    name: "Alessandra",
    time: "Comentário via Airbnb",
    date: "2024-12-03",
    stayDuration: "Ficou algumas noites",
    rating: 5,
    comment: [
      "Acomodação de muito bom gosto, clean e muito aconchegante. Com espaço amplo e bem ventilado e iluminado, cozinha bem equipada e piscina com água em ótima temperatura. ",
      "Também tinham 2 redes para relaxar e curtir os livros que estavam disponíveis. A casa faz referências a Nina Simone e Ella Fitzgerald, ajudando a criar um clima sofisticado e tranquilo, que era exatamente o que estávamos procurando. ",
      "Voltaremos! Foi excelente! Ah, e ainda tem o café da manhã de Juliana, que era uma delicia.",
    ],
    image: "/midias/testimonials/alessandra.jpg",
  },
  {
    id: 3,
    name: "Marcio",
    time: "7 anos no Airbnb",
    date: "2024-03-01",
    stayDuration: "Ficou algumas noites",
    rating: 5,
    comment: [
      "O espaço é excelente. A casa tem uma beleza muito única e muito aconchegante. Equipada com tudo que é necessário, inclusive a cozinha.",
      "A Mariângela foi muito solicita e bastante proativa em todos os nossos contatos. ",
      "Certamente voltaremos. Um local excelente para descansar!",
    ],
    image: "/midias/testimonials/marcio.webp",
  },
  {
    id: 4,
    name: "Júlya",
    time: "3 anos no Airbnb",
    date: "2024-07-01",
    stayDuration: "Ficou algumas noites",
    rating: 5,
    comment: [
      "Saímos apaixonados pelo local! A casa é linda, muito confortável e o café da manhã da Juliana é um show a parte. Sem dúvidas voltaremos!",
    ],
    image: "/midias/testimonials/julia.webp",
  },
  {
    id: 5,
    name: "João Felipe",
    time: "5 anos no Airbnb",
    date: "2024-03-01",
    stayDuration: "Ficou algumas noites",
    rating: 5,
    comment: [
      "O espaço é muito bem pensado e muito bem executado. Bom espaço para descansar e curtir com privacidade. Juliana e Val (funcionários do estabelecimento) garantem um suporte rápido, deixando a estadia melhor ainda.",
      " Pretendo retornar assim que possível! O melhor Airbnb que já fiquei na Rota! <3",
    ],
    image: "/midias/testimonials/joao-felipe.webp",
  },
  {
    id: 6,
    name: "Sandro Groisman",
    time: "Comentário via Google Place",
    date: "2024-11-01",
    stayDuration: "Ficou algumas noites",
    rating: 5,
    comment: [
      "Minha estadia na Casa Boutique Nina foi excelente. A casa é linda, bem decorada, com uma iluminação aconchegante e perfeita para relaxar. O lugar é super tranquilo, cercado de verde, com muitas janelas que deixam entrar uma brisa maravilhosa. A piscina privativa estava sempre limpa, e a privacidade do local tornou tudo ainda melhor. Dormimos super bem, o ambiente é muito confortável. ",
      "E o café da manhã preparado pela Juliana foi delicioso! Ela é muito atenciosa, sempre cuidando de cada detalhe. Sem dúvida, um lugar perfeito para descansar e desconectar. Com certeza, vou querer voltar!",
    ],
    image: "/midias/testimonials/sandro-groisman.png",
  },
  {
    id: 7,
    name: "Cristóvão",
    time: "Comentário via Airbnb",
    date: "2024-11-15",
    stayDuration: "Ficou uma noite",
    rating: 5,
    comment: ["Ótimo local, provavelmente voltarei mais vezes."],
    image: "/midias/testimonials/cristovao.webp",
  },
];

export default testimonials;
