const testimonials = [
  {
    id: 1,
    name: "Rejane",
    time: "Comentário via Airbnb",
    date: "2024-11-01",
    stayDuration: "Ficou algumas noites",
    rating: 5,
    comment: [
      "O espaço é encantador e ainda mais bonito e completo do que nas fotos. ",
      "Café da manhã delicioso feito diariamente pela Juliana, com todo o necessário. ",
      "Acomodação espaçosa e perto de uma das mais belas praias da Rota (Patacho). ",
      "Voltaria com toda a certeza!",
    ],
    image: "/midias/testimonials/rejane.webp",
  },
  {
    id: 2,
    name: "Alessandra",
    time: "Comentário via Airbnb",
    date: "2024-12-03",
    stayDuration: "Ficou algumas noites",
    rating: 5,
    comment: [
      "Acomodação de muito bom gosto, clean e muito aconchegante. Com espaço amplo e bem ventilado e iluminado, cozinha bem equipada e piscina com água em ótima temperatura. ",
      "Também tinham 2 redes para relaxar e curtir os livros que estavam disponíveis. A casa faz referências a Nina Simone e Ella Fitzgerald, ajudando a criar um clima sofisticado e tranquilo, que era exatamente o que estávamos procurando. ",
      "Voltaremos! Foi excelente! Ah, e ainda tem o café da manhã de Juliana, que era uma delicia.",
    ],
    image: "/midias/testimonials/alessandra.jpg",
  },
  {
    id: 3,
    name: "Marcio",
    time: "7 anos no Airbnb",
    date: "2024-03-01",
    stayDuration: "Ficou algumas noites",
    rating: 5,
    comment: [
      "O espaço é excelente. A casa tem uma beleza muito única e muito aconchegante. Equipada com tudo que é necessário, inclusive a cozinha.",
      "A Mariângela foi muito solicita e bastante proativa em todos os nossos contatos. ",
      "Certamente voltaremos. Um local excelente para descansar!",
    ],
    image: "/midias/testimonials/marcio.webp",
  },
  {
    id: 4,
    name: "Júlya",
    time: "3 anos no Airbnb",
    date: "2024-07-01",
    stayDuration: "Ficou algumas noites",
    rating: 5,
    comment: [
      "Saímos apaixonados pelo local! A casa é linda, muito confortável e o café da manhã da Juliana é um show a parte. Sem dúvidas voltaremos!",
    ],
    image: "/midias/testimonials/julia.webp",
  },
  {
    id: 5,
    name: "João Felipe",
    time: "5 anos no Airbnb",
    date: "2024-03-01",
    stayDuration: "Ficou algumas noites",
    rating: 5,
    comment: [
      "O espaço é muito bem pensado e muito bem executado. Bom espaço para descansar e curtir com privacidade. Juliana e Val (funcionários do estabelecimento) garantem um suporte rápido, deixando a estadia melhor ainda.",
      " Pretendo retornar assim que possível! O melhor Airbnb que já fiquei na Rota! <3",
    ],
    image: "/midias/testimonials/joao-felipe.webp",
  },
  {
    id: 6,
    name: "Sandro Groisman",
    time: "Comentário via Google Place",
    date: "2024-11-01",
    stayDuration: "Ficou algumas noites",
    rating: 5,
    comment: [
      "Minha estadia na Casa Boutique Nina foi excelente. A casa é linda, bem decorada, com uma iluminação aconchegante e perfeita para relaxar. O lugar é super tranquilo, cercado de verde, com muitas janelas que deixam entrar uma brisa maravilhosa. A piscina privativa estava sempre limpa, e a privacidade do local tornou tudo ainda melhor. Dormimos super bem, o ambiente é muito confortável. ",
      "E o café da manhã preparado pela Juliana foi delicioso! Ela é muito atenciosa, sempre cuidando de cada detalhe. Sem dúvida, um lugar perfeito para descansar e desconectar. Com certeza, vou querer voltar!",
    ],
    image: "/midias/testimonials/sandro-groisman.png",
  },
  {
    id: 7,
    name: "Cristóvão",
    time: "Comentário via Airbnb",
    date: "2024-11-15",
    stayDuration: "Ficou uma noite",
    rating: 5,
    comment: ["Ótimo local, provavelmente voltarei mais vezes."],
    image: "/midias/testimonials/cristovao.webp",
  },
];

export default testimonials;
