const galleries = [
  {
    id: 1,
    thumb: "/midias/gallery/gallerie-1/thumb-p.jpg",
    thumbBlurUrl: "/midias/gallery/gallerie-1/thumb-blur.jpg",
    title: "Conheça as Casas",
    description:
      "Descubra o equilíbrio perfeito entre charme, conforto e exclusividade. Nossa casa boutique foi projetada para proporcionar uma experiência inesquecível em cada detalhe.",
    media: [
      {
        type: "video",
        url: "/midias/gallery/gallerie-1/video-1.mp4",
        description: "Conheça as casas",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/entrada-capa.jpg",
        blurUrl: "/midias/gallery/gallerie-1/entrada-capa-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/entrada-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/entrada-1-blur.jpg",
        description: "Casa Ella à esquerda. (Entrada individual)",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/entrada-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/entrada-2-blur.jpg",
        description: "Casa Nina à direita. (Entrada individual)",
      },

      {
        type: "image",
        url: "/midias/gallery/gallerie-1/entrada-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/entrada-3-blur.jpg",
        description: "Vista para entrada",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/entrada-4-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/entrada-4-blur.jpg",
        description: "Vista para piscina",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/sala_estar-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/sala_estar-1-blur.jpg",
        description:
          "espaço para dançar, fazer alongamento, descansar, apreciar...",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/sala_estar-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/sala_estar-2-blur.jpg",
        description: "Rede para descansar",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/cozinha_completa-capa-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/cozinha_completa-capa-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/cozinha_completa-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/cozinha_completa-1-blur.jpg",
        description: "Cozinha Completa",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/cozinha_completa-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/cozinha_completa-2-blur.jpg",
        description: "Cozinha Completa",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/area_jantar-capa-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/area_jantar-capa-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/area_jantar-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/area_jantar-1-blur.jpg",
        description: "Área de Jantar",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/area_jantar-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/area_jantar-2-blur.jpg",
        description: "Área de Jantar",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/area_jantar-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/area_jantar-3-blur.jpg",
        description: "Área de Jantar",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/area_jantar-4-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/area_jantar-4-blur.jpg",
        description: "Área de Jantar",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/area_jantar-5-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/area_jantar-5-blur.jpg",
        description: "Mesa refeições no jardim",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quarto-capa-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quarto-capa-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quarto-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quarto-1-blur.jpg",
        description: "Nossa cama king",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quarto-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quarto-2-blur.jpg",
        description: "Nossa cama king",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quarto-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quarto-3-blur.jpg",
        description: "Ver TV de qualquer canto da casa",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quarto-4-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quarto-4-blur.jpg",
        description: "Ver TV de qualquer canto da casa",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quarto-5-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quarto-5-blur.jpg",
        description: "Ver TV de qualquer canto da casa",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quarto-6-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quarto-6-blur.jpg",
        description: "Detalhe da cabeceira, artesanato brasileiro.",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quarto-7-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quarto-7-blur.jpg",
        description: "Na suíte uma área de descanso na rede",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quarto-8-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quarto-8-blur.jpg",
        description: "Na suíte uma área de descanso na rede",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quarto-9-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quarto-9-blur.jpg",
        description: "Na suíte uma área de descanso na rede",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/banheiro_completo-capa-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/banheiro_completo-capa-blur.jpg",
        description: "Banheiro completo",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/banheiro_completo-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/banheiro_completo-1-blur.jpg",
        description: "Banheiro completo",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/banheiro_completo-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/banheiro_completo-2-blur.jpg",
        description: "Banheiro completo",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/banheiro_completo-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/banheiro_completo-3-blur.jpg",
        description: "Banheiro completo",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/banheiro_completo-4-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/banheiro_completo-5-blur.jpg",
        description: "Banheiro completo",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/banheiro_completo-5-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/banheiro_completo-5-blur.jpg",
        description: "Banheiro completo",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/lavabo-capa-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/lavabo-capa-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/lavabo-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/lavabo-1-blur.jpg",
        description: "Lavabo da piscina",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quintal-capa-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quintal-capa-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quintal-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quintal-1-blur.jpg",
        description: "Vista da piscina com área gourmet",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quintal-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quintal-2-blur.jpg",
        description: "Vista da piscina com área gourmet",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quintal-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quintal-3-blur.jpg",
        description: "Vista da piscina com área gourmet",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quintal-4-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quintal-4-blur.jpg",
        description: "Vista da piscina com área gourmet",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/patio-capa-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/patio-capa-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/patio-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/patio-1-blur.jpg",
        description: "Iluminação noturna",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/patio-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/patio-2-blur.jpg",
        description: "Iluminação noturna",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/patio-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/patio-3-blur.jpg",
        description: "Iluminação noturna",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/patio-4-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/patio-4-blur.jpg",
        description: "Iluminação noturna",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/patio-5-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/patio-5-blur.jpg",
        description: "Iluminação noturna",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/patio-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/patio-1-blur.jpg",
        description: "Iluminação noturna",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/patio-6-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/patio-6-blur.jpg",
        description: "Iluminação noturna",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/patio-7-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/patio-7-blur.jpg",
        description: "Visão dos fundos",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/patio-8-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/patio-8-blur.jpg",
        description:
          "Área de sol com espreguiçadeiras e rede. Sombra e água fresca",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/exterior-capa-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/exterior-capa-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/exterior-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/exterior-1-blur.jpg",
        description: "Nascer do sol na praia do Patacho",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/exterior-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/exterior-2-blur.jpg",
        description: "Nascer do sol na praia do Patacho",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/fundos-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/fundos-1-blur.jpg",
        description: "Fundos",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/fundos-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/fundos-2-blur.jpg",
        description: "Fundos",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/fundos-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/fundos-3-blur.jpg",
        description: "Fundos",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/piscina-capa-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/piscina-capa-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/piscina-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/piscina-1-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/piscina-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/piscina-2-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/piscina-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/piscina-3-blur.jpg",
        description: "Vista da suíte (ou casa principal)",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/piscina-4-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/piscina-4-blur.jpg",
        description: "Vista da suíte (ou casa principal)",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/piscina-5-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/piscina-5-blur.jpg",
        description: "Vista da suíte (ou casa principal)",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/piscina-6-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/piscina-6-blur.jpg",
        description:
          "Área de sol com espreguiçadeiras e rede. Sombra e água fresca",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/piscina-7-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/piscina-7-blur.jpg",
        description:
          "Área de sol com espreguiçadeiras e rede. Sombra e água fresca",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/piscina-8-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/piscina-8-blur.jpg",
        description:
          "Área de sol com espreguiçadeiras e rede. Sombra e água fresca",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/piscina-9-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/piscina-9-blur.jpg",
        description:
          "Área de sol com espreguiçadeiras e rede. Sombra e água fresca",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/churrasqueira-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/churrasqueira-1-blur.jpg",
        description:
          "Churrasqueira e utensílios para preparar aquele churrasco",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/mesa_jardin-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/mesa_jardin-1-blur.jpg",
        description: "Mesa refeições no jardim",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/mesa_jardin-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/mesa_jardin-2-blur.jpg",
        description: "Mesa refeições no jardim",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/mesa_jardin-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/mesa_jardin-2-blur.jpg",
        description: "No closet, roupões personalizados",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/mesa_jardin-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/mesa_jardin-2-blur.jpg",
        description: "Closet",
      },
    ],
  },

  {
    id: 2,
    thumb: "/midias/gallery/gallerie-2/thumb-2-p.jpg",
    thumbBlurUrl: "/midias/gallery/gallerie-2/thumb-2-blur.jpg",
    title: "Ambientes Internos",
    description:
      "Ambientes aconchegantes e funcionais que combinam estilo e modernidade. Viva momentos únicos em cada espaço cuidadosamente planejado.",
    media: [
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/image-6-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/image-6-blur.jpg",
        description: "Legenda da imagem 6",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/image-7-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/image-7-blur.jpg",
        description: "Legenda da imagem 7",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/image-8-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/image-8-blur.jpg",
        description: "Legenda da imagem 8",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/image-9-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/image-9-blur.jpg",
        description: "Legenda da imagem 9",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/image-10-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/image-10-blur.jpg",
        description: "Legenda da imagem 10",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/image-22-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/image-22-blur.jpg",
        description: "Legenda da imagem 22",
      },
      {
        type: "video",
        url: "/midias/gallery/gallerie-2/video-2.mp4",
        description: "Legenda do vídeo 2",
      },
      {
        type: "video",
        url: "/midias/gallery/gallerie-2/video-3.mp4",
        description: "Legenda do vídeo 3",
      },
    ],
  },
  {
    id: 3,
    thumb: "/midias/gallery/gallerie-3/thumb-3-p.jpg",
    thumbBlurUrl: "/midias/gallery/gallerie-3/thumb-3-blur.jpg",
    title: "Área de Lazer",
    description:
      "Relaxe e se divirta em nossa área de lazer privativa, projetada para oferecer momentos de descanso com vista para a beleza natural ao seu redor.",
    media: [
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/image-11-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/image-11-blur.jpg",
        description: "Legenda da imagem 11",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/image-12-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/image-12-blur.jpg",
        description: "Legenda da imagem 12",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/image-13-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/image-13-blur.jpg",
        description: "Legenda da imagem 13",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/image-14-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/image-14-blur.jpg",
        description: "Legenda da imagem 14",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/image-15-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/image-15-blur.jpg",
        description: "Legenda da imagem 15",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/image-16-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/image-16-blur.jpg",
        description: "Legenda da imagem 16",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/image-17-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/image-17-blur.jpg",
        description: "Legenda da imagem 17",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/image-18-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/image-18-blur.jpg",
        description: "Legenda da imagem 18",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/image-19-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/image-19-blur.jpg",
        description: "Legenda da imagem 19",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/image-20-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/image-20-blur.jpg",
        description: "Legenda da imagem 20",
      },
      {
        type: "video",
        url: "/midias/gallery/gallerie-3/video-1.mp4",
        description: "Legenda do vídeo 1",
      },
      {
        type: "video",
        url: "/midias/gallery/gallerie-3/video-2.mp4",
        description: "Legenda do vídeo 2",
      },
      {
        type: "video",
        url: "/midias/gallery/gallerie-3/video-3.mp4",
        description: "Legenda do vídeo 3",
      },
    ],
  },
  {
    id: 4,
    thumb: "/midias/gallery/gallerie-4/thumb-4-p.jpg",
    thumbBlurUrl: "/midias/gallery/gallerie-4/thumb-4-blur.jpg",
    title: "Experiência Gastronômica",
    description:
      "Desfrute de momentos únicos ao redor da mesa. Nossa cozinha e espaço para refeições foram pensados para criar memórias saborosas.",
    media: [
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/image-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/image-1-blur.jpg",
        description: "Legenda da imagem 1",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/image-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/image-2-blur.jpg",
        description: "Legenda da imagem 2",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/image-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/image-3-blur.jpg",
        description: "Legenda da imagem 3",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/image-4-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/image-4-blur.jpg",
        description: "Legenda da imagem 4",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/image-5-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/image-5-blur.jpg",
        description: "Legenda da imagem 5",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/image-6-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/image-6-blur.jpg",
        description: "Legenda da imagem 6",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/image-7-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/image-7-blur.jpg",
        description: "Legenda da imagem 7",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/image-8-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/image-8-blur.jpg",
        description: "Legenda da imagem 8",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/image-9-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/image-9-blur.jpg",
        description: "Legenda da imagem 9",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/image-10-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/image-10-blur.jpg",
        description: "Legenda da imagem 10",
      },
      {
        type: "video",
        url: "/midias/gallery/gallerie-4/video-4.mp4",
        description: "Legenda do vídeo 4",
      },
      {
        type: "video",
        url: "/midias/gallery/gallerie-4/video-5.mp4",
        description: "Legenda do vídeo 5",
      },
    ],
  },
  {
    id: 5,
    thumb: "/midias/gallery/gallerie-5/thumb-5-p.jpg",
    thumbBlurUrl: "/midias/gallery/gallerie-5/thumb-5-blur.jpg",
    title: "Localização e Vista",
    description:
      "Encante-se com a localização privilegiada e as vistas deslumbrantes que fazem deste lugar o refúgio perfeito para relaxar e se conectar com a natureza.",
    media: [
      {
        type: "image",
        url: "/midias/gallery/gallerie-5/image-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-5/image-1-blur.jpg",
        description: "Legenda da imagem 1",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-5/image-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-5/image-2-blur.jpg",
        description: "Legenda da imagem 2",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-5/image-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-5/image-3-blur.jpg",
        description: "Legenda da imagem 3",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-5/image-4-p.jpg",
        blurUrl: "/midias/gallery/gallerie-5/image-4-blur.jpg",
        description: "Legenda da imagem 4",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-5/image-5-p.jpg",
        blurUrl: "/midias/gallery/gallerie-5/image-5-blur.jpg",
        description: "Legenda da imagem 5",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-5/image-21-p.jpg",
        blurUrl: "/midias/gallery/gallerie-5/image-21-blur.jpg",
        description: "Legenda da imagem 21",
      },
      {
        type: "video",
        url: "/midias/gallery/gallerie-5/video-1.mp4",
        description: "Legenda do vídeo 1",
      },
    ],
  },
  {
    id: 6,
    thumb: "/midias/gallery/gallerie-6/thumb-6-p.jpg",
    thumbBlurUrl: "/midias/gallery/gallerie-6/thumb-6-blur.jpg",
    title: "Café da Manhã",
    description:
      "Comece o dia da melhor forma com um café da manhã preparado com carinho, acompanhado pela tranquilidade e beleza de Alagoas.",
    media: [
      {
        type: "image",
        url: "/midias/gallery/gallerie-6/image-6-p.jpg",
        blurUrl: "/midias/gallery/gallerie-6/image-6-blur.jpg",
        description: "Legenda da imagem 6",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-6/image-7-p.jpg",
        blurUrl: "/midias/gallery/gallerie-6/image-7-blur.jpg",
        description: "Legenda da imagem 7",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-6/image-8-p.jpg",
        blurUrl: "/midias/gallery/gallerie-6/image-8-blur.jpg",
        description: "Legenda da imagem 8",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-6/image-9-p.jpg",
        blurUrl: "/midias/gallery/gallerie-6/image-9-blur.jpg",
        description: "Legenda da imagem 9",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-6/image-10-p.jpg",
        blurUrl: "/midias/gallery/gallerie-6/image-10-blur.jpg",
        description: "Legenda da imagem 10",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-6/image-22-p.jpg",
        blurUrl: "/midias/gallery/gallerie-6/image-22-blur.jpg",
        description: "Legenda da imagem 22",
      },
      {
        type: "video",
        url: "/midias/gallery/gallerie-6/video-2.mp4",
        description: "Legenda do vídeo 2",
      },
      {
        type: "video",
        url: "/midias/gallery/gallerie-6/video-3.mp4",
        description: "Legenda do vídeo 3",
      },
    ],
  },
];

export default galleries;
