const galleries = [
  {
    id: 1,
    thumb: "/midias/gallery/gallerie-1/thumb-1-p.jpg",
    thumbBlurUrl: "/midias/gallery/gallerie-1/thumb-1-blur.jpg",
    title: "Galeria 1",
    description: "alguma descrição",
    media: [
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/image-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/image-1-blur.jpg",
        description: "Legenda da imagem 1",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/image-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/image-2-blur.jpg",
        description: "Legenda da imagem 2",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/image-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/image-3-blur.jpg",
        description: "Legenda da imagem 3",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/image-4-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/image-4-blur.jpg",
        description: "Legenda da imagem 4",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/image-5-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/image-5-blur.jpg",
        description: "Legenda da imagem 5",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/image-21-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/image-21-blur.jpg",
        description: "Legenda da imagem 21",
      },
      {
        type: "video",
        url: "/midias/gallery/gallerie-1/video-1.mp4",
        description: "Legenda do vídeo 1",
      },
    ],
  },
  {
    id: 2,
    thumb: "/midias/gallery/gallerie-2/thumb-2-p.jpg",
    thumbBlurUrl: "/midias/gallery/gallerie-2/thumb-2-blur.jpg",
    title: "Galeria 2",
    description: "alguma descrição",
    media: [
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/image-6-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/image-6-blur.jpg",
        description: "Legenda da imagem 6",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/image-7-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/image-7-blur.jpg",
        description: "Legenda da imagem 7",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/image-8-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/image-8-blur.jpg",
        description: "Legenda da imagem 8",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/image-9-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/image-9-blur.jpg",
        description: "Legenda da imagem 9",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/image-10-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/image-10-blur.jpg",
        description: "Legenda da imagem 10",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/image-22-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/image-22-blur.jpg",
        description: "Legenda da imagem 22",
      },
      {
        type: "video",
        url: "/midias/gallery/gallerie-2/video-2.mp4",
        description: "Legenda do vídeo 2",
      },
      {
        type: "video",
        url: "/midias/gallery/gallerie-2/video-3.mp4",
        description: "Legenda do vídeo 3",
      },
    ],
  },
  {
    id: 3,
    thumb: "/midias/gallery/gallerie-3/thumb-3-p.jpg",
    thumbBlurUrl: "/midias/gallery/gallerie-3/thumb-3-blur.jpg",
    title: "Galeria 3",
    description: "alguma descrição",
    media: [
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/image-11-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/image-11-blur.jpg",
        description: "Legenda da imagem 11",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/image-12-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/image-12-blur.jpg",
        description: "Legenda da imagem 12",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/image-13-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/image-13-blur.jpg",
        description: "Legenda da imagem 13",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/image-14-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/image-14-blur.jpg",
        description: "Legenda da imagem 14",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/image-15-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/image-15-blur.jpg",
        description: "Legenda da imagem 15",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/image-16-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/image-16-blur.jpg",
        description: "Legenda da imagem 16",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/image-17-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/image-17-blur.jpg",
        description: "Legenda da imagem 17",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/image-18-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/image-18-blur.jpg",
        description: "Legenda da imagem 18",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/image-19-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/image-19-blur.jpg",
        description: "Legenda da imagem 19",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/image-20-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/image-20-blur.jpg",
        description: "Legenda da imagem 20",
      },
      {
        type: "video",
        url: "/midias/gallery/gallerie-3/video-1.mp4",
        description: "Legenda do vídeo 1",
      },
      {
        type: "video",
        url: "/midias/gallery/gallerie-3/video-2.mp4",
        description: "Legenda do vídeo 2",
      },
      {
        type: "video",
        url: "/midias/gallery/gallerie-3/video-3.mp4",
        description: "Legenda do vídeo 3",
      },
    ],
  },
  {
    id: 4,
    thumb: "/midias/gallery/gallerie-4/thumb-4-p.jpg",
    thumbBlurUrl: "/midias/gallery/gallerie-4/thumb-4-blur.jpg",
    title: "Galeria 4",
    description: "alguma descrição",
    media: [
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/image-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/image-1-blur.jpg",
        description: "Legenda da imagem 1",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/image-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/image-2-blur.jpg",
        description: "Legenda da imagem 2",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/image-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/image-3-blur.jpg",
        description: "Legenda da imagem 3",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/image-4-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/image-4-blur.jpg",
        description: "Legenda da imagem 4",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/image-5-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/image-5-blur.jpg",
        description: "Legenda da imagem 5",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/image-6-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/image-6-blur.jpg",
        description: "Legenda da imagem 6",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/image-7-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/image-7-blur.jpg",
        description: "Legenda da imagem 7",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/image-8-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/image-8-blur.jpg",
        description: "Legenda da imagem 8",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/image-9-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/image-9-blur.jpg",
        description: "Legenda da imagem 9",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/image-10-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/image-10-blur.jpg",
        description: "Legenda da imagem 10",
      },
      {
        type: "video",
        url: "/midias/gallery/gallerie-4/video-4.mp4",
        description: "Legenda do vídeo 4",
      },
      {
        type: "video",
        url: "/midias/gallery/gallerie-4/video-5.mp4",
        description: "Legenda do vídeo 5",
      },
    ],
  },
  {
    id: 5,
    thumb: "/midias/gallery/gallerie-5/thumb-5-p.jpg",
    thumbBlurUrl: "/midias/gallery/gallerie-5/thumb-5-blur.jpg",
    title: "Galeria 5",
    description: "alguma descrição",
    media: [
      {
        type: "image",
        url: "/midias/gallery/gallerie-5/image-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-5/image-1-blur.jpg",
        description: "Legenda da imagem 1",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-5/image-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-5/image-2-blur.jpg",
        description: "Legenda da imagem 2",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-5/image-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-5/image-3-blur.jpg",
        description: "Legenda da imagem 3",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-5/image-4-p.jpg",
        blurUrl: "/midias/gallery/gallerie-5/image-4-blur.jpg",
        description: "Legenda da imagem 4",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-5/image-5-p.jpg",
        blurUrl: "/midias/gallery/gallerie-5/image-5-blur.jpg",
        description: "Legenda da imagem 5",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-5/image-21-p.jpg",
        blurUrl: "/midias/gallery/gallerie-5/image-21-blur.jpg",
        description: "Legenda da imagem 21",
      },
      {
        type: "video",
        url: "/midias/gallery/gallerie-5/video-1.mp4",
        description: "Legenda do vídeo 1",
      },
    ],
  },
  {
    id: 6,
    thumb: "/midias/gallery/gallerie-6/thumb-6-p.jpg",
    thumbBlurUrl: "/midias/gallery/gallerie-6/thumb-6-blur.jpg",
    title: "Galeria 6",
    description: "alguma descrição",
    media: [
      {
        type: "image",
        url: "/midias/gallery/gallerie-6/image-6-p.jpg",
        blurUrl: "/midias/gallery/gallerie-6/image-6-blur.jpg",
        description: "Legenda da imagem 6",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-6/image-7-p.jpg",
        blurUrl: "/midias/gallery/gallerie-6/image-7-blur.jpg",
        description: "Legenda da imagem 7",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-6/image-8-p.jpg",
        blurUrl: "/midias/gallery/gallerie-6/image-8-blur.jpg",
        description: "Legenda da imagem 8",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-6/image-9-p.jpg",
        blurUrl: "/midias/gallery/gallerie-6/image-9-blur.jpg",
        description: "Legenda da imagem 9",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-6/image-10-p.jpg",
        blurUrl: "/midias/gallery/gallerie-6/image-10-blur.jpg",
        description: "Legenda da imagem 10",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-6/image-22-p.jpg",
        blurUrl: "/midias/gallery/gallerie-6/image-22-blur.jpg",
        description: "Legenda da imagem 22",
      },
      {
        type: "video",
        url: "/midias/gallery/gallerie-6/video-2.mp4",
        description: "Legenda do vídeo 2",
      },
      {
        type: "video",
        url: "/midias/gallery/gallerie-6/video-3.mp4",
        description: "Legenda do vídeo 3",
      },
    ],
  },
];

export default galleries;
