const galleries = [
  {
    id: 1,
    thumb: "/midias/gallery/gallerie-1/thumb-p.jpg",
    thumbBlurUrl: "/midias/gallery/gallerie-1/thumb-blur.jpg",
    title: "Conheça as Casas",
    description:
      "Descubra o equilíbrio perfeito entre charme, conforto e exclusividade. Nossa casa boutique foi projetada para proporcionar uma experiência inesquecível em cada detalhe.",
    media: [
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/sobre-as-casas-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/sobre-as-casas-1-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/entrada-capa-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/entrada-capa-blur.jpg",
        description: "",
      },
      {
        type: "video",
        url: "/midias/gallery/gallerie-1/video-1.mp4",
        description: "Conheça as casas",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/entrada-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/entrada-1-blur.jpg",
        description: "Casa Ella à esquerda. (Entrada individual)",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/entrada-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/entrada-2-blur.jpg",
        description: "Casa Nina à direita. (Entrada individual)",
      },

      {
        type: "image",
        url: "/midias/gallery/gallerie-1/entrada-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/entrada-3-blur.jpg",
        description: "Vista para entrada",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/entrada-4-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/entrada-4-blur.jpg",
        description: "Vista para piscina",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/sala_estar-capa-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/sala_estar-capa-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/sala_estar-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/sala_estar-1-blur.jpg",
        description:
          "espaço para dançar, fazer alongamento, descansar, apreciar...",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/sala_estar-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/sala_estar-2-blur.jpg",
        description: "Rede para descansar",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/cozinha_completa-capa-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/cozinha_completa-capa-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/cozinha_completa-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/cozinha_completa-1-blur.jpg",
        description: "Cozinha Completa",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/cozinha_completa-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/cozinha_completa-2-blur.jpg",
        description: "Cozinha Completa",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/cozinha_completa-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/cozinha_completa-3-blur.jpg",
        description: "Cozinha Completa",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/area_jantar-capa-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/area_jantar-capa-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/area_jantar-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/area_jantar-1-blur.jpg",
        description: "Área de Jantar",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/area_jantar-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/area_jantar-2-blur.jpg",
        description: "Área de Jantar",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/area_jantar-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/area_jantar-3-blur.jpg",
        description: "Área de Jantar",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/area_jantar-4-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/area_jantar-4-blur.jpg",
        description: "Área de Jantar",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/area_jantar-5-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/area_jantar-5-blur.jpg",
        description: "Mesa refeições no jardim",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quarto-capa-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quarto-capa-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quarto-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quarto-1-blur.jpg",
        description: "Nossa cama king",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quarto-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quarto-2-blur.jpg",
        description: "Nossa cama king",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quarto-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quarto-3-blur.jpg",
        description: "Ver TV de qualquer canto da casa",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quarto-4-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quarto-4-blur.jpg",
        description: "Ver TV de qualquer canto da casa",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quarto-5-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quarto-5-blur.jpg",
        description: "Ver TV de qualquer canto da casa",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quarto-6-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quarto-6-blur.jpg",
        description: "Detalhe da cabeceira, artesanato brasileiro.",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quarto-7-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quarto-7-blur.jpg",
        description: "Na suíte uma área de descanso na rede",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quarto-8-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quarto-8-blur.jpg",
        description: "Na suíte uma área de descanso na rede",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quarto-9-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quarto-9-blur.jpg",
        description: "Na suíte uma área de descanso na rede",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/banheiro_completo-capa-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/banheiro_completo-capa-blur.jpg",
        description: "Banheiro completo",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/banheiro_completo-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/banheiro_completo-1-blur.jpg",
        description: "Banheiro completo",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/banheiro_completo-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/banheiro_completo-2-blur.jpg",
        description: "Banheiro completo",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/banheiro_completo-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/banheiro_completo-3-blur.jpg",
        description: "Banheiro completo",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/banheiro_completo-4-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/banheiro_completo-5-blur.jpg",
        description: "Banheiro completo",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/banheiro_completo-5-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/banheiro_completo-5-blur.jpg",
        description: "Banheiro completo",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/banheiro_completo-6-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/banheiro_completo-6-blur.jpg",
        description: "Banheiro completo",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/banheiro_completo-7-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/banheiro_completo-7-blur.jpg",
        description: "Banheiro completo",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/lavabo-capa-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/lavabo-capa-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/lavabo-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/lavabo-1-blur.jpg",
        description: "Lavabo da piscina",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quintal-capa-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quintal-capa-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quintal-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quintal-1-blur.jpg",
        description: "Vista da piscina com área gourmet",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quintal-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quintal-2-blur.jpg",
        description: "Vista da piscina com área gourmet",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quintal-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quintal-3-blur.jpg",
        description: "Vista da piscina com área gourmet",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/quintal-4-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/quintal-4-blur.jpg",
        description: "Vista da piscina com área gourmet",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/patio-capa-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/patio-capa-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/patio-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/patio-1-blur.jpg",
        description: "Iluminação noturna",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/patio-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/patio-2-blur.jpg",
        description: "Iluminação noturna",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/patio-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/patio-3-blur.jpg",
        description: "Iluminação noturna",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/patio-4-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/patio-4-blur.jpg",
        description: "Iluminação noturna",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/patio-5-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/patio-5-blur.jpg",
        description: "Iluminação noturna",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/patio-6-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/patio-6-blur.jpg",
        description: "Iluminação noturna",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/patio-7-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/patio-7-blur.jpg",
        description:
          "Área de sol com espreguiçadeiras e rede. Sombra e água fresca",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/fundos-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/fundos-1-blur.jpg",
        description: "Fundos",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/fundos-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/fundos-2-blur.jpg",
        description: "Fundos",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/fundos-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/fundos-3-blur.jpg",
        description: "Fundos",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/fundos-4-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/fundos-4-blur.jpg",
        description: "Fundos",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/piscina-capa-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/piscina-capa-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/piscina-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/piscina-1-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/piscina-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/piscina-2-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/piscina-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/piscina-3-blur.jpg",
        description: "Vista da suíte (ou casa principal)",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/piscina-4-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/piscina-4-blur.jpg",
        description: "Vista da suíte (ou casa principal)",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/piscina-5-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/piscina-5-blur.jpg",
        description: "Vista da suíte (ou casa principal)",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/piscina-6-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/piscina-6-blur.jpg",
        description:
          "Área de sol com espreguiçadeiras e rede. Sombra e água fresca",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/piscina-7-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/piscina-7-blur.jpg",
        description:
          "Área de sol com espreguiçadeiras e rede. Sombra e água fresca",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/piscina-8-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/piscina-8-blur.jpg",
        description:
          "Área de sol com espreguiçadeiras e rede. Sombra e água fresca",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/piscina-9-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/piscina-9-blur.jpg",
        description:
          "Área de sol com espreguiçadeiras e rede. Sombra e água fresca",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/churrasqueira-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/churrasqueira-1-blur.jpg",
        description:
          "Churrasqueira e utensílios para preparar aquele churrasco",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/mesa_jardin-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/mesa_jardin-1-blur.jpg",
        description: "Mesa refeições no jardim",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/mesa_jardin-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/mesa_jardin-2-blur.jpg",
        description: "Mesa refeições no jardim",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/closet-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/closet-1-blur.jpg",
        description: "No closet, roupões personalizados",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/closet-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/closet-2-blur.jpg",
        description: "Closet",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-1/closet-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-1/closet-3-blur.jpg",
        description: "Closet",
      },
    ],
  },
  {
    id: 2,
    thumb: "/midias/gallery/gallerie-2/thumb-p.jpg",
    thumbBlurUrl: "/midias/gallery/gallerie-2/thumb-blur.jpg",
    title: "Café da Manhã",
    description:
      "Ambientes aconchegantes e funcionais que combinam estilo e modernidade. Viva momentos únicos em cada espaço cuidadosamente planejado.",
    media: [
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/capa-cafe-da-manha-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/capa-cafe-da-manha-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/cafe-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/cafe-1-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/cafe-2-a-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/cafe-2-a-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/cafe-2-b-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/cafe-2-b-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/cafe-2-c-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/cafe-2-c-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/cafe-3-a-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/cafe-3-a-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/cafe-3-b-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/cafe-3-b-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/cafe-4-a-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/cafe-4-a-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/cafe-4-b-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/cafe-4-b-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/cafe-4-c-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/cafe-4-c-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/cafe-5-a-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/cafe-5-a-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/cafe-5-b-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/cafe-5-b-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/cafe-6-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/cafe-6-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/cafe-7-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/cafe-7-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/cafe-8-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/cafe-8-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-2/cafe-9-p.jpg",
        blurUrl: "/midias/gallery/gallerie-2/cafe-9-blur.jpg",
        description: "",
      },
    ],
  },
  {
    id: 3,
    thumb: "/midias/gallery/gallerie-3/thumb-p.jpg",
    thumbBlurUrl: "/midias/gallery/gallerie-3/thumb-blur.jpg",
    title: "Área de Lazer",
    description:
      "Relaxe e se divirta em nossa área de lazer privativa, projetada para oferecer momentos de descanso com vista para a beleza natural ao seu redor.",
    media: [
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/capa-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/capa-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/kit-cadeirapraia-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/kit-cadeirapraia-1-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/kit-cadeirapraia-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/kit-cadeirapraia-2-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/kit-cadeirapraia-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/kit-cadeirapraia-3-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/rede-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/rede-1-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/rede-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/rede-2-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/rede-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/rede-3-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/cadeiraspiscina-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/cadeiraspiscina-1-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/cadeiraspiscina-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/cadeiraspiscina-2-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/cadeiraspiscina-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/cadeiraspiscina-3-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/cadeiraspiscina-4-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/cadeiraspiscina-4-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/cadeiraspiscina-5-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/cadeiraspiscina-5-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/piscina-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/piscina-1-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/piscina-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/piscina-2-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/piscina-3-a-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/piscina-3-a-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/piscina-3-b-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/piscina-3-b-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/piscina-4-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/piscina-4-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/bar-1-a-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/bar-1-a-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/bar-1-b-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/bar-1-b-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/cozinha-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/cozinha-1-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/patio-1-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/patio-1-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/sala-1-a-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/sala-1-a-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/sala-1-b-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/sala-1-b-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/quarto-1-a-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/quarto-1-a-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-3/quarto-1-b-p.jpg",
        blurUrl: "/midias/gallery/gallerie-3/quarto-1-b-blur.jpg",
        description: "",
      },
    ],
  },
  {
    id: 4,
    thumb: "/midias/gallery/gallerie-4/thumb-p.jpg",
    thumbBlurUrl: "/midias/gallery/gallerie-4/thumb-blur.jpg",
    title: "Praias e Passeios",
    description:
      "Desfrute de momentos únicos ao redor da mesa. Nossa cozinha e espaço para refeições foram pensados para criar memórias saborosas.",
    media: [
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/capa-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/capa-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/capapatacho-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/capapatacho-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/patacho-1-a-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/patacho-1-a-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/patacho-1-b-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/patacho-1-b-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/patacho-2-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/patacho-2-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/patacho-3-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/patacho-3-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/patacho-4-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/patacho-4-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/patacho-5-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/patacho-5-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/patacho-6-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/patacho-6-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/patacho-7-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/patacho-7-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/patacho-8-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/patacho-8-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/capaPraiadalaje-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/capaPraiadalaje-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/capaPasseiosdejangada-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/capaPasseiosdejangada-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/capaVisitaSantuario-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/capaVisitaSantuario-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/capaFarolPortoDepedras-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/capaFarolPortoDepedras-blur.jpg",
        description: "",
      },
      {
        type: "image",
        url: "/midias/gallery/gallerie-4/capaTatuamunha-p.jpg",
        blurUrl: "/midias/gallery/gallerie-4/capaTatuamunha-blur.jpg",
        description: "",
      },
    ],
  },
];

export default galleries;
